### ISSUE TITLE
uninitialized constant Puma::HAS_SSL (NameError)

### ISSUE THREAD

**Issue by lain0** [emad-elsaid/rubrowser#20]
puma is installed  but it requires ssl params , but how to use it wothout ssl locally? 
```
rubrowser -slocalhost:8080 > output.html                                         
Traceback (most recent call last):
	29: from /Users/serj/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
	28: from /Users/serj/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
	27: from /Users/serj/.rvm/gems/ruby-2.6.4/bin/rubrowser:23:in `<main>'
	26: from /Users/serj/.rvm/gems/ruby-2.6.4/bin/rubrowser:23:in `load'
	25: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/rubrowser-2.9.1/bin/rubrowser:5:in `<top (required)>'
	24: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	23: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	22: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/rubrowser-2.9.1/lib/rubrowser.rb:2:in `<top (required)>'
	21: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	20: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	19: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/rubrowser-2.9.1/lib/rubrowser/monitor.rb:2:in `<top (required)>'
	18: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/rubrowser-2.9.1/lib/rubrowser/server.rb:4:in `<top (required)>'
	15: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	14: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	13: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/puma-5.2.2/lib/puma/launcher.rb:5:in `<top (required)>'
	12: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	11: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	10: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/puma-5.2.2/lib/puma/cluster.rb:3:in `<top (required)>'
	 9: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 8: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 7: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/puma-5.2.2/lib/puma/runner.rb:3:in `<top (required)>'
	 6: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 5: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 4: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/puma-5.2.2/lib/puma/server.rb:11:in `<top (required)>'
	 3: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 2: from /Users/serj/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	 1: from /Users/serj/.rvm/gems/ruby-2.6.4/gems/puma-5.2.2/lib/puma/binder.rb:10:in `<top (required)>'
/Users/serj/.rvm/gems/ruby-2.6.4/gems/puma-5.2.2/lib/puma/binder.rb:12:in `<module:Puma>': uninitialized constant Puma::HAS_SSL (NameError)
```

**Comment by emad-elsaid** [comment]
Hey @lain0 thanks for reporting this. I'll try to reproduce it on my machine first, if you can provide me with some docker container or something that reproduces this issue that would be super

**Comment by lain0** [comment]
docker say no more)
Dockerfile
```Dockerfile
FROM ruby:2.7-alpine3.13

# RUN bundle config --global frozen 1
# RUN apk add --update alpine-sdk build-base

COPY Gemfile ./
WORKDIR /usr/src/app
RUN apk --no-cache add --virtual build-dependencies ruby-dev ruby-bundler build-base \
    && bundle install && bundle clean --force \
    && apk del build-dependencies \
    && rm -rf /usr/lib/ruby/gems/*/cache/* \
          /var/cache/apk/* \
          /tmp/* \
          /var/tmp/*

COPY . .
CMD ["rubrows"]
```

build: ``` docker build -t rubrowser .```
run:  ```docker run -it rubrowser rubrowser```

error:
```
docker run -it rubrowser rubrowser                                                               1 ↵  10014  11:03:48
Traceback (most recent call last):
	27: from /usr/local/bundle/bin/rubrowser:23:in `<main>'
	26: from /usr/local/bundle/bin/rubrowser:23:in `load'
	25: from /usr/local/bundle/gems/rubrowser-2.9.1/bin/rubrowser:5:in `<top (required)>'
	24: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	23: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	22: from /usr/local/bundle/gems/rubrowser-2.9.1/lib/rubrowser.rb:2:in `<top (required)>'
	21: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	20: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	19: from /usr/local/bundle/gems/rubrowser-2.9.1/lib/rubrowser/monitor.rb:2:in `<top (required)>'
	18: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	17: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	16: from /usr/local/bundle/gems/rubrowser-2.9.1/lib/rubrowser/server.rb:4:in `<top (required)>'
	15: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	14: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	13: from /usr/local/bundle/gems/puma-5.2.2/lib/puma/launcher.rb:5:in `<top (required)>'
	12: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	11: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	10: from /usr/local/bundle/gems/puma-5.2.2/lib/puma/cluster.rb:3:in `<top (required)>'
	 9: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 8: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 7: from /usr/local/bundle/gems/puma-5.2.2/lib/puma/runner.rb:3:in `<top (required)>'
	 6: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 4: from /usr/local/bundle/gems/puma-5.2.2/lib/puma/server.rb:11:in `<top (required)>'
	 3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 1: from /usr/local/bundle/gems/puma-5.2.2/lib/puma/binder.rb:10:in `<top (required)>'
/usr/local/bundle/gems/puma-5.2.2/lib/puma/binder.rb:12:in `<module:Puma>': uninitialized constant Puma::HAS_SSL (NameError)
```

**Comment by lain0** [comment]
And your .travisCI.yml does not include ruby 2.6 2.7 3.0. 
I didn't try it with ruby < 2.6.4, maybe it's not supposed to work with up versions?

**Comment by emad-elsaid** [comment]
yeah I see I was requiring puma specific parts, I required all of puma now in the gem for the monitoring feature and pushed a new version

**Comment by emad-elsaid** [comment]
I changed travis and the required ruby version to >2.5 and fixes rubocop issues. and released a new version
